language: node_js
sudo: required
services:
  - docker
node_js:
  - "7"
script:
  - npm run build
  - docker build -t halversondm/toilet-training-tracker .
notifications:
  slack:
    secure: ST/Z4BtREzWL8DOI22v92pNb+oNmfDwTPH4uz2tHFE+/rreFTstVjIysJpEwrQAqyuIA2V3Rhzx0qYItyauT8KVSYHsbY4GIgABja8tWC1hT31pNoOYBXcfKfi9Vcn0QNJDkQPNSGLmpG8HTDPjK7qqkwPA6zjc1fnzi9F2758JUSX8gPcU8GPEqKwjiP3haKA5jiyt1bJ/n0/ub9Wic8hE2gSsRZzJCeA8f915RVXh0xHdL8/z6W0Ng9vwu1KUrWxOe2c6gelZnJTUypHI0/PPy9tZtowd/5xLwJL64iohM7UH+sVIK7fTa8a7noqnduxkRdji01vYDP6J+0VluJQ3b4VmaaGeRQwpsIBs9iN4NcgmvBFrE3MH5PRFXdLOHATCy8EoZeKBdv1BWec2Koaq2bVkj7oYqMGfcLnoi2NFOoSL2T1mGrJIpjbjFX/PIMQ8oyWSah0H/0KTK7kPbXZFiEYqP/kG93enljwzPlNhdC2xWKOsVGur9oCfr5YIN8w8Jgehkk+hfN3BezOyec+UfBxfu6wtDO+P7/vCW5mrJnbmlznuZRwTltJmJiQTFUt2Oagvr5Xtm9E6y1ige+FInklI11Ka8p8yo7A9q+bLy5O0WgJP/tsGgAGCDt7DHDjVldWuBdVwc4HoaZgBHl3r9wsMdZh+EmxA69XA38hg=
